2024-Summer-Bootcamp-Team-O/Frontend

src/App.tsx
src/main.tsx
src/pages/LoginPage.tsx
src/pages/RegisterPage.tsx

[design/#12] 회원가입 페이지 구현
#설명
- 회원가입 페이지 퍼블리싱
#작업내용
- figma 토대로 tailwind css 적용하여 회원가입 페이지 구현

design: 회원가입 페이지 구현

---

src/components/FeedBackLuModal.tsx
src/components/FeedBackMoModal.tsx
src/pages/LoginPage.tsx
src/pages/LunchTalkPage.tsx
src/pages/MainPage.tsx
src/pages/MorningPage.tsx
src/pages/RegisterPage.tsx
src/pages/StartPage.tsx

#설명
- 페이지 라우팅 적용
#작업내용
- 페이지 라우팅 적용
close #53

[design/#53] 페이지 라우팅 적용

---

src/components/FeedBackMoModal.tsx
src/components/ResultLoadingModal.tsx
src/index.css
src/pages/LoginPage.tsx
src/pages/RegisterPage.tsx
src/pages/ResultPage.tsx

#설명
- 디자인 세부 수정 및 기타 코드 수
#작업내용
- 엔드 포인트 수정
- 결과페이지에서 메인으로 돌아가는 버튼 추가
- 기존 hover옵션 이상 수정
- 로그인, 회원가입 placeholder 텍스트 크기 수정
close #57

[design/#57]: 디자인 수정 및 코드 수정

---

package-lock.json
src/pages/LoginPage.tsx

#설명
- 로그인 api 연동
#작업내용
- 로그인 페이지에 axios 이용하여 로그인 api 연동
close #59

[feat/#59] 로그인 api 연동

---

src/components/CharacterModal.tsx
src/index.css
src/pages/LoginPage.tsx
src/pages/RegisterPage.tsx
src/pages/ResultPage.tsx
src/pages/StartPage.tsx

#설명
- 디자인 및 코드 수정
#작업내용
- CharacterModal 코드 수정
- StartPage에 gradient 속성 수정
- login 내 element 위치 조정
- login, email id입력창 placeholder 메시지 수정
close #62

 [design/#62] 로그인, 회원가입 및 디자인 수정

---

src/components/LLoadingModal.tsx
src/pages/RegisterPage.tsx
src/pages/ResultPage.tsx
yarn.lock

#설명
- 회원가입 api 연동
#작업내용
- 회원가입 api 연동
close #60

[feat/#60] 회원가입 api 연동 

---

src/components/CharacterModal.tsx
src/pages/MainPage.tsx
src/pages/MorningPage.tsx

#설명
- 대화 시작 api 연동
#작업내용
-  대화 시작 및 api 연동, 캐릭터 배정을 위한 코드 수정
-  캐릭터 이미지 변경을 위한 코드 추가
close #64

[feat/#] 대화 시작 api 연동

---

src/pages/RegisterPage.tsx

#설명
- 아이디 중복확인 api 연동
#작업내용
- 아이디 중복확인 api 연동
close #66

[feat/#66] 아이디 중복확인 api 연동

---

src/components/CharacterModal.tsx
src/components/FeedBackEvModal.tsx
src/components/FeedBackLuModal.tsx
src/components/FeedBackMoModal.tsx
src/pages/EveningPage.tsx
src/pages/LunchTalkPage.tsx
src/pages/MainPage.tsx
src/pages/MorningPage.tsx
src/pages/RegisterPage.tsx

#설명
- 다음 상황 api 연동
- 캐릭터 id 다음 페이지 전달
#작업내용
- 다음 상황으로 넘기기 위한 api 연동
- 캐릭터 id를 세션 스토리지에 저장해 다른 페이지에서 사용할 수 있도록 변경
close #76

 [feat/#76] 다음 상황 api 연동

---

src/components/CameraModal.tsx
src/pages/MorningPage.tsx

#설명
- 사원증 사진 등록 api 연동
#작업내용
- 웹캠을 이용한 사원증 image 전송, 응답 확인
close #78

 [feat/#78] 사원증 사진 등록 api 연동

---

src/components/FeedBackMoModal.tsx
src/pages/LunchTalkPage.tsx
src/pages/MainPage.tsx
src/pages/MorningPage.tsx

#설명
- 점심 대화페이지 웹소켓 연결
- 사용자 답변 입력 가능
- 대사 스트미링 형식으로 넘어와요~~
#작업내용
- 점심 대화페이지 웹소켓 연결
- 다음 상황 api 연동
close #84

[feat/#84] 점심 대화페이지 웹소켓 연결 & 다음 상황 api 연동

---

src/pages/EveningPage.tsx

#설명
- 저녁페이지 다음 상황 api 연동
- 사용자 답변 입력 가능
- 답변, 대사 스트리밍 구현
- 드디어 끄으읏~~~!!!
#작업내용
- 저녁페이지 다음 상황 api 연동
- 사용자 답변 입력 가능
- 답변, 대사 스트리밍 구현
close #89

[feat/#89] 저녁페이지 다음 상황 api 연동

---

src/pages/EveningPage.tsx

#설명
- 피드백 받기 버튼 누르면 대사가 넘어오는 이슈 발견 ~
- 제대로 수정했어요~

[feat/#89] 저녁페이지 코드 수정

---

src/pages/EveningPage.tsx
src/pages/LunchPage.tsx
src/pages/RegisterPage.tsx
src/pages/ResultPage.tsx

#설명
- 토큰 미적용 코드들에 jwt 토큰 일괄 적용 
#작업내용
- axiosInstance를 이용해 jwt 토큰 일괄 적용 
- resultPage api 이중 호출되는 문제 수정
close #94

[feat/#94]  jwt 토큰 일괄 적용 

---

.gitignore
index.d.ts
index.html
src/pages/EveningPage.tsx
src/pages/LunchPage.tsx
src/pages/ResultPage.tsx
tsconfig.json

#설명
- ResultPage에서 공유버튼 클릭 시 카카오톡에 메시지 형태로 공유되도록 구현
#작업내용
- 카카오 api 사용하여 공유하기 구현

[feat/#96] 카카오 공유하기 구현

---

src/components/CameraModal.tsx
src/components/FeedBackEvModal.tsx
src/components/FeedBackLuModal.tsx
src/components/FeedBackMoModal.tsx
src/hooks/axiosInstance.ts
src/pages/EveningPage.tsx
src/pages/LoginPage.tsx
src/pages/LunchPage.tsx
src/pages/MorningPage.tsx
src/pages/MyPage.tsx
src/pages/RegisterPage.tsx
src/pages/ResultPage.tsx

#설명
- 피드백 api 연동
- 토큰 적용 안된 거 적용하기
#작업내용
- 피드백 api 연동
- 토큰 적용 안된 거 적용하기
close #92

[feat/#92] 피드백 api 연동 및 토큰 적용

---

src/pages/EveningPage.tsx
src/pages/LunchPage.tsx
src/pages/MorningPage.tsx

#설명
- 캐릭터 대사, 답변 음성 적용
- 피드백 대사 음성 적용
#작업내용
- 음성 적용 끄으으읏!!!
close #100

[feat/#100] 캐릭터 대사 음성 적용

---

src/pages/MainPage.tsx
src/pages/MyPage.tsx

#설명
- 기존 페이지에 로그아웃 버튼 추가
#작업내용
- MainPage 로그아웃 버튼 추가
- MyPage 로그아웃 버튼 추가
close #105

[design/#105] 로그아웃 버튼 추가

---

index.html
src/pages/MainPage.tsx
src/pages/MyPage.tsx

#설명
- 로그아웃 api 연동
#작업내용
- MyPage, MainPage 로그아웃 api 연동
close #107

[feat/#107] 로그아웃 api 연동 

---

src/pages/EveningPage.tsx
src/pages/LunchPage.tsx
src/pages/MorningPage.tsx

#설명
- 캐릭터가 말하는 도중에 사용자가 입력하지 못하도록 수정
#작업내용
- 대사 종료를 기점으로 사용자 입력을 활성화하는 코드 추가
close #110

[fix/#110] 시뮬레이션 중 사용자 입력 문제해결

---

src/pages/EveningPage.tsx
src/pages/LunchPage.tsx
src/pages/MorningPage.tsx

#설명
- 피드백 버튼 잠금 설정
#작업내용
- 피드백 버튼 잠금 설정
close #106

[fix/#106] 피드백 버튼 잠금 설정

---

src/pages/LoginPage.tsx

#설명
- 로그인 에러메시지 수정
#작업내용
- 로그인 400 에러메시지 수정
close #113

[fix/#113]  로그인 에러 메세지 수정

---

src/App.tsx
src/pages/EveningPage.tsx
src/pages/LunchPage.tsx
src/pages/MorningPage.tsx
src/pages/MyPage.tsx

#설명
- 버튼 효과음 적용
#작업내용
- 버튼 효과음 적용
close #120

[design/#120] 버튼 효과음 적용

---

src/components/CameraModal.tsx
src/hooks/axiosInstance.ts
src/pages/EveningPage.tsx
src/pages/LoginPage.tsx
src/pages/LunchPage.tsx
src/pages/MainPage.tsx
src/pages/MorningPage.tsx
src/pages/MyPage.tsx
src/pages/RegisterPage.tsx
src/pages/ResultPage.tsx
src/pages/SharedResultPage.tsx

#설명
- api 호출 로컬에서 서버로 변경
#작업내용
- 기존에  로컬에서 api 호출하던 것을 전부 서버로 변경
close #126

[refactor/#126]: api 호출 변경

---

src/components/CameraModal.tsx
src/components/CharacterModal.tsx
src/components/ResultLoadingModal.tsx
src/pages/EveningPage.tsx
src/pages/LoginPage.tsx
src/pages/LunchPage.tsx
src/pages/MorningPage.tsx
src/pages/MyPage.tsx
src/pages/RegisterPage.tsx
src/pages/ResultPage.tsx
src/pages/SharedResultPage.tsx
src/pages/StartPage.tsx
src/pages/UserResultPage.tsx

#설명
- 기존 방식대로 했을 경우 s3에 표시되지않는 문제 해결을 위해 에셋 적용을 import로 변경
#작업내용
- 에셋이 사용되는 부분 경로를 전부 import로 변경
close #130

[fix/#130] asset적용 import로 변경

---

src/pages/UserResultPage.tsx
src/utils/shareKakao.ts

#설명
- UserResultPage 두 버튼 오류 수정
#작업내용
- UserResultPage 버튼에 누락된 속성 추가
close #140

[fix/#140] UserResultPage 버튼 오류 수정

---

src/pages/MyPage.tsx

#설명
- 결과모달 반응형 적용하려다가 마이페이지 반응형 적용함
#작업내용
- 마이페이지 반응형 적용
close #164

[design/#164]: 마이페이지 반응형 적용

---

src/pages/MainPage.tsx
src/pages/MyPage.tsx

#설명
- 반응형 수정
#작업내용
-
(이슈에 대한 작업완료시) close #181

[design/#181]:반응형 수정

---

src/pages/SharedResultPage.tsx

#설명
- 공유결과페이지 반응형 적용
- 마지막이었음 좋겠어요~
#작업내용
-

[design/#183] 공유결과페이지 반응형 적용
